name: Azure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to ACR
          uses: azure/docker-login@v1
          with:
            login-server: ebiznes-fgggcab8ahe0arc9.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Build and push image
          run: |
            docker build . -t ebiznes-fgggcab8ahe0arc9.azurecr.io/frontend:${{ github.sha }}
            docker push ebiznes-fgggcab8ahe0arc9.azurecr.io/frontend:${{ github.sha }}

        - name: Send email notification
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: ${{ secrets.MAIL_SERVER }}
            server_port: 465
            username: ${{ secrets.MAIL_USERNAME }}
            password: ${{ secrets.MAIL_PASSWORD }}
            subject: Deployment Notification
            to: ${{ secrets.MAIL_ADDRESS }}
            from: GitHub Actions <ci@example.com>
            body: |
              Frontend built successfully.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
